nodePool:
  # -- Name of this node pool
  name: custom-nodepool
  # -- Compute location (region for a regional cluster or zone for a zonal cluster)
  location: us-central1
  autoscaling:
    # -- Minimum node count
    minNodeCount: 2
    # -- Maximum node count
    maxNodeCount: 3
  nodeConfig:
    # -- Machine type
    machineType: n1-standard-2
    # -- Disk Size in GB
    diskSizeGb: 100
    # -- Disk type
    diskType: pd-standard
    shieldedInstanceConfig:
      enableSecureBoot: false
      enableIntegrityMonitoring: false
    serviceAccountRef: folder-admin@nth-subset-372600.iam.gserviceaccount.com
