apiVersion: v2
name: iam-service-accounts
description: A Helm Chart for creating GCP service accounts and assigning roles
type: application
version: 0.2.0
appVersion: "0.2.0"
maintainers:
  - email: gab.120gg@gmail.com
    name: Gabriel Garoz
    url: 
