{{- range $sa, $value := .Values.serviceAccounts }}
{{- range $projectRoles, $role := $value.projectRoles }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ $sa }}-role-{{ regexFind "[^.]+$" (lower $role) }}
  namespace: {{ .Values.global.projectId }}
spec:
  member: serviceAccount:{{ $sa }}@{{ .Values.global.projectId }}.iam.gserviceaccount.com
  role: roles/{{ $role }}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1  
    kind: Project
    external: projects/{{ .Values.global.projectId }}
{{- end }}    
{{- end }}
