{{- range $key, $value := .Values.principals }}
{{ if eq $value.create true }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.global.projectId }}
spec:
  displayName: {{ $value.displayName }}
{{ end }}  
{{- end }}
