apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    label-one: "value-one"
  name: {{ default "containernodepool-sample-basic" .Values.nodePool.name }}
  namespace: {{ .Values.global.projectId }}  
spec:
  location: {{ default "us-central1" .Values.nodePool.location }}
  autoscaling:
    minNodeCount: {{ default 1 .Values.nodePool.minNodeCount }}
    maxNodeCount: {{ default 3 .Values.nodePool.maxNodeCount }}
  nodeConfig:
    machineType: {{ default "n1-standard-1" .Values.nodePool.machineType }}
    diskSizeGb: {{ default "100" .Values.nodePool.diskSizeGb }}
    diskType: {{ default "pd-standard" .Values.nodePool.diskType }}
    tags:
      - tagone
      - tagtwo
    preemptible: false
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {{ default "standard-cluster" .Values.global.clusterName }}