apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    label-one: "value-one"
  name: {{ default "containernodepool-sample-basic" .Values.nodePool.name }}
  namespace: {{ .Values.global.projectId }}
spec:
  location: {{ default "us-central1" .Values.nodePool.location }}
  autoscaling:
    minNodeCount: {{ default 1 .Values.nodePool.minNodeCount }}
    maxNodeCount: {{ default 3 .Values.nodePool.maxNodeCount }}
  nodeConfig:
    machineType: {{ default "n1-standard-1" .Values.nodePool.nodeConfig.machineType }}
    diskSizeGb: {{ default "100" .Values.nodePool.nodeConfig.diskSizeGb }}
    diskType: {{ default "pd-standard" .Values.nodePool.nodeConfig.diskType }}
    shieldedInstanceConfig:
      enableSecureBoot: {{ default false .Values.nodePool.nodeConfig.enableSecureBoot }}
      enableIntegrityMonitoring: {{ default false .Values.nodePool.nodeConfig.enableIntegrityMonitoring }}
    serviceAccountRef:
      external: {{ .Values.nodePool.nodeConfig.serviceAccountRef }}
      
    tags: {{ .Values.nodePool.nodeConfig.tags }}
    preemptible: false
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    metadata:
      disable-legacy-endpoints: "true"
    bootDiskKMSCryptoKeyRef:
      external: {{ default "" .Values.nodePool.nodeConfig.bootDiskKMSCryptoKeyRef }}
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {{ default "standard-cluster" .Values.global.clusterName }}