apiVersion: v2
name: apis
description: A Helm Chart for enabling API services
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - email: gab.120gg@gmail.com
    name: Gabriel Garoz
    url: 
